import Mathlib
import SortingProofs.MergeSort
import SortingProofs.InsertionSort
set_option linter.style.header false

/-!
# Comparing Proof Techniques: Merge Sort vs Insertion Sort

This file is the analytical core of the project. We compare two proof
strategies side by side:

1. **Functional induction** (`fun_induction`): follows the recursion of
   the function itself. Used for merge sort proofs.

2. **Structural induction**: follows the structure of the data type (List).
   Used for insertion sort proofs.

The key question: does the proof technique match the algorithm structure?
-/

/-!
## Observation 1: Case Structure

Merge sort's `fun_induction` generates 3 cases:
- empty list
- singleton list
- list with 2+ elements (the actual recursive case)

Insertion sort's structural induction generates 2 cases:
- nil
- cons

This reflects a real difference: merge sort needs to pattern match on
two elements at once to decide how to split, so its recursion principle
has an extra base case. Structural induction on lists never sees this.
-/

/-!
## Observation 2: Where Automation Helps

For merge sort length, the hard case (2+ elements) closed with:
  `simp_all; omega`

Lean's `omega` tactic handles the arithmetic about list lengths after
splitting. We never had to think about the inequality manually.

For insertion sort length, we used:
  `rw [insert'_length]; omega`

Same `omega` at the end, but we had to manually rewrite using our own
lemma first. Merge sort's functional induction gave us the split lemmas
for free via the subtype trick (carrying length proofs in the type).
-/

/-!
## Observation 3: Permutation Proofs

Merge sort permutation: one line, `List.mergeSort_perm xs le`.
Mathlib already has it. Nothing to prove.

Insertion sort permutation: we had to build it from scratch.
- `insert'_perm`: induction on the list, two cases (le a x or not),
  one closes by `rfl`, other by composing `Perm.cons` and `Perm.swap`.
- `insertionSort_perm`: induction + composing `insert'_perm` with the IH.

The interesting thing: `Perm.swap` is the primitive that says
swapping two adjacent elements is a permutation. Insertion sort
literally does adjacent swaps, so the proof mirrors the algorithm.
Merge sort's permutation proof is hidden inside Mathlib because it's
more complex — it goes through the merge operation's properties.
-/

/-!
## Observation 4: Sortedness Proofs

This is where the real difference shows up.

Merge sort sortedness: `List.pairwise_mergeSort le htrans htotal xs`
Again, Mathlib handles it, but only after we supply transitivity and
totality proofs. The theorem statement tells us what the algorithm needs:
a total, transitive ordering.

Insertion sort sortedness: we had to prove two lemmas first.
- `insert'_pairwise`: the hard one. Inserting `a` into a sorted list
  stays sorted. Two sub-cases:
  - `le a x = true`: `a` goes at the front. We use transitivity to
    show `a ≤ everything_else` via `a ≤ x ≤ everything_else`.
  - `le a x = false`: `a` goes somewhere later. We use totality to
    derive `le x a`, then show the head `x` is still ≤ everything
    in the inserted tail via the membership lemma `insert'_mem`.
- `insertionSort_sorted`: induction + `insert'_pairwise`.

The sortedness proof for insertion sort is longer because we own the
implementation. We can't appeal to a black box — we have to reason
about exactly what `insert'` does to the list structure.
-/

/-!
## Observation 5: Proof Length Comparison

| Theorem          | MergeSort | InsertionSort |
|------------------|-----------|---------------|
| length           | 4 lines   | 5 lines       |
| permutation      | 1 line    | 8 lines       |
| sortedness       | 4 lines   | 25 lines      |
| helper lemmas    | 0         | 15 lines      |
| **total**        | ~9 lines  | ~53 lines     |

The disparity in sortedness is the most interesting result.
Merge sort's sortedness is short because Mathlib's proof works at the
level of the merge operation's invariants. Our insertion sort proof
works at the level of individual list elements. Neither is "better" —
they reflect different levels of abstraction.
-/

/-!
## Observation 6: What Functional Induction Actually Buys You

`fun_induction xs.mergeSort le` is syntactic sugar for:
`induction xs using List.mergeSort.fun_cases_unfolding le`

The `fun_cases_unfolding` principle is auto-generated by Lean from the
definition of `mergeSort`. It gives you:
- The same case split as the function definition
- Induction hypotheses that match the recursive calls exactly
- Length facts about the sublists as hypotheses (from the subtype)

Without it, you would need to manually unfold `mergeSort`, case split,
and reconstruct the induction hypotheses. That's exactly what we did
for insertion sort — and the proof is 6x longer as a result.

The lesson: when proving things about a function, induct on the function's
own recursion principle, not on the data type. `fun_induction` makes this
the default for well-founded recursive functions in Lean 4.
-/

-- ============================================
-- Concrete demonstration: same theorem, two ways
-- ============================================

-- We prove length preservation for a simple recursive function
-- both with structural induction and with fun_induction,
-- to make the difference concrete and runnable.

def myMap {α β : Type*} (f : α → β) : List α → List β
  | []      => []
  | x :: xs => f x :: myMap f xs

-- Structural induction proof
theorem myMap_length_structural {α β : Type*} (f : α → β) (xs : List α) :
    (myMap f xs).length = xs.length := by
  induction xs with
  | nil => simp [myMap]
  | cons x xs ih =>
    simp [myMap, ih]

-- Functional induction proof
theorem myMap_length_functional {α β : Type*} (f : α → β) (xs : List α) :
    (myMap f xs).length = xs.length := by
  fun_induction myMap f xs
  · simp [*]
  · simp [*]

/-!
Both proofs work. For `myMap` they're the same length because the
function's recursion exactly mirrors the list structure. The divergence
happens when the function's recursion does NOT mirror the list structure
— like merge sort splitting into two halves. That's when `fun_induction`
wins decisively.
-/
